name: Power Outage Checker (POE.PL.UA)

on:
  schedule:
    - cron: '0 * * * *'  # Кожну годину о :00
  workflow_dispatch:     # Дозволяє запускати вручну

jobs:
  check-schedule:
    runs-on: ubuntu-latest
    env:
      PROXY_URL: ${{ http://91.238.104.172:2024 }}  # Наприклад: http://user:pass@ip:port або socks5://...
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Power Outage Parser via Proxy
        run: python poe_parser.py
        env:
          http_proxy: ${{ env.PROXY_URL }}
          https_proxy: ${{ env.PROXY_URL }}
          HTTP_PROXY: ${{ env.PROXY_URL }}
          HTTPS_PROXY: ${{ env.PROXY_URL }}

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: schedule-result
          path: result_*.txt
          retention-days: 7
